"""add city names to trackings

Revision ID: edc6a084e30a
Revises: 27c0fb88eb9c
Create Date: 2024-01-18 23:31:56.198195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc6a084e30a'
down_revision: Union[str, None] = '27c0fb88eb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackings', sa.Column('from_city_name', sa.String(), nullable=False))
    op.add_column('trackings', sa.Column('to_city_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackings', 'to_city_name')
    op.drop_column('trackings', 'from_city_name')
    # ### end Alembic commands ###
