"""add telegram_message_id in tracking_notifications and last_expire_notification_sent_at in users

Revision ID: 0931a9f12530
Revises: cb03e65d245c
Create Date: 2024-02-23 09:54:19.716111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0931a9f12530'
down_revision: Union[str, None] = 'cb03e65d245c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_notifications', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_expire_notification_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_expire_notification_sent_at')
    op.drop_column('tracking_notifications', 'telegram_message_id')
    # ### end Alembic commands ###
