"""add site_codes to trackings

Revision ID: cb03e65d245c
Revises: edc6a084e30a
Create Date: 2024-02-04 00:49:04.715184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb03e65d245c'
down_revision: Union[str, None] = 'edc6a084e30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackings', sa.Column('from_city_site_code', sa.String(), nullable=False))
    op.add_column('trackings', sa.Column('to_city_site_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackings', 'to_city_site_code')
    op.drop_column('trackings', 'from_city_site_code')
    # ### end Alembic commands ###
