"""telegram_message_id make not optional in tracking_notifications

Revision ID: f83e260e938f
Revises: 0931a9f12530
Create Date: 2024-02-23 10:13:24.955858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83e260e938f'
down_revision: Union[str, None] = '0931a9f12530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracking_notifications', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracking_notifications', 'telegram_message_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
